sonar.organization=nicolasomar
sonar.projectKey=NicolasOmar_react-key-generator

# relative paths to source directories. More details and properties are described
# in https://sonarcloud.io/documentation/project-administration/narrowing-the-focus/
sonar.inclusions=index.ts
sonar.test.inclusions=index.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info